// ============================================================
// PeoplePulse — tRPC Compliance & ITW Reporting Router
// ITW-7 (monthly), ITW-10 (annual), ITW-8 (on-demand)
// Alerts: ITW-7 on 10th monthly, ITW-10 at 30 & 7 days before 31 July
// ============================================================

import { z } from "zod";
import { router, orgProcedure, superAdminProcedure } from "../trpc";
import { TRPCError } from "@trpc/server";

// ---------------------------------------------------------------
// HELPERS
// ---------------------------------------------------------------

/**
 * Generate ITW-7 CSV format as expected by BURS e-TAX portal
 * Format: EMP_ID, OMANG, NAME, GROSS, TAXABLE, PAYE, SDL, NET
 */
function generateITW7CSV(
  lines: Array<{
    employee: { employeeNumber: string; omang: string | null; firstName: string; lastName: string };
    grossPay: number;
    taxableIncome: number;
    paye: number;
    sdl: number;
    netPay: number;
  }>,
  periodMonth: number,
  periodYear: number
): string {
  const header = "EMP_ID,OMANG,SURNAME,OTHER_NAMES,GROSS,TAXABLE_INCOME,PAYE,SDL,NET_PAY";
  const rows = lines.map((l) =>
    [
      l.employee.employeeNumber,
      l.employee.omang ?? "N/A",
      l.employee.lastName.toUpperCase(),
      l.employee.firstName.toUpperCase(),
      l.grossPay.toFixed(2),
      l.taxableIncome.toFixed(2),
      l.paye.toFixed(2),
      l.sdl.toFixed(2),
      l.netPay.toFixed(2),
    ].join(",")
  );

  return [header, ...rows].join("\n");
}

/**
 * Generate ITW-10 CSV for annual employer return
 */
function generateITW10CSV(
  orgName: string,
  bursTin: string,
  lines: Array<{
    employee: { employeeNumber: string; omang: string | null; firstName: string; lastName: string; bursTpn: string | null };
    ytdGross: number;
    ytdPaye: number;
  }>
): string {
  const header = "EMPLOYER_NAME,EMPLOYER_TIN,EMP_ID,OMANG,SURNAME,OTHER_NAMES,BURS_TPN,YTD_GROSS,YTD_PAYE";
  const rows = lines.map((l) =>
    [
      orgName.toUpperCase(),
      bursTin,
      l.employee.employeeNumber,
      l.employee.omang ?? "N/A",
      l.employee.lastName.toUpperCase(),
      l.employee.firstName.toUpperCase(),
      l.employee.bursTpn ?? "N/A",
      l.ytdGross.toFixed(2),
      l.ytdPaye.toFixed(2),
    ].join(",")
  );

  return [header, ...rows].join("\n");
}

/**
 * Generate ITW-8 for a single employee (annual certificate)
 */
function generateITW8Text(
  employee: {
    firstName: string;
    lastName: string;
    omang: string | null;
    bursTpn: string | null;
    employmentType: string;
    startDate: Date;
  },
  orgName: string,
  bursTin: string,
  ytdGross: number,
  ytdPaye: number,
  periodYear: number
): string {
  return `INCOME TAX CERTIFICATE (ITW-8)
=================================
Tax Year: ${periodYear}

Employer Details:
  Name: ${orgName}
  BURS TIN: ${bursTin}

Employee Details:
  Surname: ${employee.lastName}
  Other Names: ${employee.firstName}
  Omang/ID: ${employee.omang ?? "N/A"}
  BURS TPN: ${employee.bursTpn ?? "N/A"}
  Employment Type: ${employee.employmentType}
  Start Date: ${employee.startDate.toLocaleDateString("en-GB")}

Earnings Summary:
  YTD Gross Pay: P${ytdGross.toLocaleString("en-US", { minimumFractionDigits: 2 })}
  YTD PAYE Deducted: P${ytdPaye.toLocaleString("en-US", { minimumFractionDigits: 2 })}

This certificate is issued in terms of the Income Tax Act Cap. 52:01.

=================================
Generated by PeoplePulse — Smart HR. Botswana Built.
`;
}

// ---------------------------------------------------------------
// ROUTER
// ---------------------------------------------------------------

export const complianceRouter = router({
  // ─── ITW-7: Monthly payroll return ────────────────────────────
  generateITW7: orgProcedure
    .input(
      z.object({
        periodMonth: z.number().int().min(1).max(12),
        periodYear: z.number().int().min(2024),
        format: z.enum(["CSV", "JSON"]).default("CSV"),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const orgId = ctx.auth.organizationId!;

      // Find locked payroll run for this period
      const run = await ctx.prisma.payrollRun.findFirst({
        where: {
          organizationId: orgId,
          periodMonth: input.periodMonth,
          periodYear: input.periodYear,
          status: "LOCKED",
        },
        include: {
          lines: {
            include: {
              employee: {
                select: {
                  employeeNumber: true,
                  omang: true,
                  firstName: true,
                  lastName: true,
                },
              },
            },
          },
        },
      });

      if (!run) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: `No locked payroll run found for ${input.periodMonth}/${input.periodYear}.`,
        });
      }

      if (input.format === "CSV") {
        const csv = generateITW7CSV(run.lines as never, input.periodMonth, input.periodYear);
        return {
          format: "CSV",
          content: csv,
          fileName: `ITW7_${input.periodYear}_${String(input.periodMonth).padStart(2, "0")}.csv`,
          periodMonth: input.periodMonth,
          periodYear: input.periodYear,
        };
      }

      // JSON format
      return {
        format: "JSON",
        content: run.lines.map((l) => ({
          empId: l.employee.employeeNumber,
          omang: l.employee.omang,
          name: `${l.employee.firstName} ${l.employee.employeeNumber}`,
          gross: Number(l.grossPay),
          taxable: Number(l.taxableIncome),
          paye: Number(l.paye),
          sdl: Number(l.sdl),
          net: Number(l.netPay),
        })),
        periodMonth: input.periodMonth,
        periodYear: input.periodYear,
      };
    }),

  // ─── ITW-10: Annual employer return (July) ────────────────────
  generateITW10: orgProcedure
    .input(
      z.object({
        periodYear: z.number().int().min(2024),
        format: z.enum(["CSV", "JSON"]).default("CSV"),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const orgId = ctx.auth.organizationId!;

      const org = await ctx.prisma.organization.findUnique({
        where: { id: orgId },
        select: { name: true, bursTin: true },
      });

      // Get all locked runs for the financial year (July–June)
      const runs = await ctx.prisma.payrollRun.findMany({
        where: {
          organizationId: orgId,
          periodYear: input.periodYear,
          status: "LOCKED",
        },
        include: {
          lines: {
            include: {
              employee: {
                select: {
                  employeeNumber: true,
                  omang: true,
                  firstName: true,
                  lastName: true,
                  bursTpn: true,
                },
              },
            },
          },
        },
      });

      if (runs.length === 0) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: `No locked payroll runs found for tax year ${input.periodYear}.`,
        });
      }

      // Aggregate YTD per employee
      const employeeTotals: Record<
        string,
        { employee: (typeof runs)[0]["lines"][0]["employee"]; ytdGross: number; ytdPaye: number }
      > = {};

      for (const run of runs) {
        for (const line of run.lines) {
          const empId = line.employeeId;
          if (!employeeTotals[empId]) {
            employeeTotals[empId] = {
              employee: line.employee as never,
              ytdGross: 0,
              ytdPaye: 0,
            };
          }
          employeeTotals[empId].ytdGross += Number(line.grossPay);
          employeeTotals[empId].ytdPaye += Number(line.paye);
        }
      }

      const aggregated = Object.values(employeeTotals);

      if (input.format === "CSV") {
        const csv = generateITW10CSV(
          org!.name,
          org!.bursTin,
          aggregated as never,
        );
        return {
          format: "CSV",
          content: csv,
          fileName: `ITW10_${input.periodYear}_${org!.bursTin}.csv`,
          periodYear: input.periodYear,
          employeeCount: aggregated.length,
        };
      }

      return {
        format: "JSON",
        content: aggregated.map((a) => ({
          ...a,
          ytdGross: Number(a.ytdGross.toFixed(2)),
          ytdPaye: Number(a.ytdPaye.toFixed(2)),
        })),
        periodYear: input.periodYear,
        employeeCount: aggregated.length,
      };
    }),

  // ─── ITW-8: On-demand employee tax certificate ─────────────────
  generateITW8: orgProcedure
    .input(
      z.object({
        employeeId: z.string(),
        format: z.enum(["TEXT", "JSON"]).default("TEXT"),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const orgId = ctx.auth.organizationId!;

      const employee = await ctx.prisma.employee.findFirst({
        where: { id: input.employeeId, organizationId: orgId },
      });

      if (!employee) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Employee not found." });
      }

      const org = await ctx.prisma.organization.findUnique({
        where: { id: orgId },
        select: { name: true, bursTin: true },
      });

      // Get YTD from all locked runs this year
      const runs = await ctx.prisma.payrollRun.findMany({
        where: { organizationId: orgId, status: "LOCKED" },
        include: { lines: { where: { employeeId: input.employeeId } } },
      });

      let ytdGross = 0;
      let ytdPaye = 0;
      const currentYear = new Date().getFullYear();

      for (const run of runs) {
        if (run.periodYear === currentYear) {
          for (const line of run.lines) {
            ytdGross += Number(line.grossPay);
            ytdPaye += Number(line.paye);
          }
        }
      }

      const text = generateITW8Text(
        employee as never,
        org!.name,
        org!.bursTin,
        ytdGross,
        ytdPaye,
        currentYear
      );

      return {
        format: input.format,
        content: input.format === "TEXT" ? text : { ytdGross, ytdPaye },
        employeeId: input.employeeId,
        employeeName: `${employee.firstName} ${employee.lastName}`,
      };
    }),

  // ─── Compliance Dashboard Data ───────────────────────────────
  getDashboard: orgProcedure.query(async ({ ctx }) => {
    const orgId = ctx.auth.organizationId!;

    // Employees missing BURS TPN
    const missingTPN = await ctx.prisma.employee.count({
      where: {
        organizationId: orgId,
        status: "ACTIVE",
        bursTpn: null,
      },
    });

    // Work permits expiring within 30/14/7 days
    const today = new Date();
    const in30Days = new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000);
    const in14Days = new Date(today.getTime() + 14 * 24 * 60 * 60 * 1000);
    const in7Days = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000);

    const expiringPermits = await ctx.prisma.employee.findMany({
      where: {
        organizationId: orgId,
        status: "ACTIVE",
        workPermitExpiry: { not: null, lte: in30Days },
      },
      select: {
        id: true,
        firstName: true,
        lastName: true,
        workPermitExpiry: true,
        workPermitNumber: true,
      },
      orderBy: { workPermitExpiry: "asc" },
    });

    // Fixed-term contracts expiring within 30 days
    const in30DaysFromNow = new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000);
    const expiringContracts = await ctx.prisma.employee.findMany({
      where: {
        organizationId: orgId,
        status: "ACTIVE",
        employmentType: "FIXED_TERM",
        endDate: { not: null, lte: in30DaysFromNow },
      },
      select: {
        id: true,
        firstName: true,
        lastName: true,
        endDate: true,
        employmentType: true,
      },
    });

    // YTD PAYE total
    const currentYear = today.getFullYear();
    const ytdPayeRuns = await ctx.prisma.payrollRun.findMany({
      where: { organizationId: orgId, status: "LOCKED", periodYear: currentYear },
      select: { totalPaye: true },
    });

    const ytdPayeTotal = ytdPayeRuns.reduce((sum, r) => sum + Number(r.totalPaye), 0);

    // Next PAYE due (15th of next month)
    const nextPayeDue = new Date(today.getFullYear(), today.getMonth() + 1, 15);
    const daysUntilPayeDue = Math.ceil(
      (nextPayeDue.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)
    );

    // Payroll runs this period
    const currentMonth = today.getMonth() + 1;
    const currentPeriodRun = await ctx.prisma.payrollRun.findFirst({
      where: {
        organizationId: orgId,
        periodMonth: currentMonth,
        periodYear: currentYear,
      },
      select: { id: true, status: true },
    });

    return {
      missingTPNCount: missingTPN,
      expiringWorkPermits: expiringPermits.map((e) => ({
        ...e,
        workPermitExpiry: e.workPermitExpiry?.toISOString(),
        alertLevel:
          e.workPermitExpiry && e.workPermitExpiry <= in7Days
            ? "CRITICAL"
            : e.workPermitExpiry && e.workPermitExpiry <= in14Days
              ? "HIGH"
              : "MEDIUM",
      })),
      expiringContracts: expiringContracts.map((e) => ({
        ...e,
        endDate: e.endDate?.toISOString(),
      })),
      ytdPayeTotal: Number(ytdPayeTotal.toFixed(2)),
      nextPayeDue: nextPayeDue.toISOString(),
      daysUntilPayeDue: Math.max(0, daysUntilPayeDue),
      currentPayrollStatus: currentPeriodRun?.status ?? "NOT_STARTED",
    };
  }),

  // ─── Create compliance alert ───────────────────────────────────
  createAlert: orgProcedure
    .input(
      z.object({
        employeeId: z.string().optional(),
        type: z.enum([
          "WORK_PERMIT_EXPIRY",
          "CONTRACT_EXPIRY",
          "PROBATION_END",
          "ITW7_DUE",
          "ITW10_DUE",
          "FIXED_TERM_EXPIRY",
          "LEAVE_NOT_TAKEN",
          "MISSING_BURS_TPN",
        ]),
        title: z.string(),
        message: z.string(),
        dueDate: z.string().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const orgId = ctx.auth.organizationId!;

      const alert = await ctx.prisma.alert.create({
        data: {
          organizationId: orgId,
          employeeId: input.employeeId ?? null,
          type: input.type,
          title: input.title,
          message: input.message,
          dueDate: input.dueDate ? new Date(input.dueDate) : null,
        },
      });

      return { alertId: alert.id };
    }),

  // ─── List active alerts ────────────────────────────────────────
  listAlerts: orgProcedure
    .input(
      z.object({
        employeeId: z.string().optional(),
        type: z.string().optional(),
        unacknowledgedOnly: z.boolean().default(false),
      })
    )
    .query(async ({ ctx, input }) => {
      const where: Record<string, unknown> = { organizationId: ctx.auth.organizationId! };
      if (input.employeeId) where.employeeId = input.employeeId;
      if (input.type) where.type = input.type;
      if (input.unacknowledgedOnly) where.acknowledgedAt = null;

      const alerts = await ctx.prisma.alert.findMany({
        where,
        orderBy: { createdAt: "desc" },
        take: 50,
      });

      return alerts;
    }),

  // ─── Acknowledge alert ─────────────────────────────────────────
  acknowledgeAlert: orgProcedure
    .input(z.object({ alertId: z.string() }))
    .mutation(async ({ ctx, input }) => {
      const alert = await ctx.prisma.alert.findFirst({
        where: { id: input.alertId, organizationId: ctx.auth.organizationId! },
      });

      if (!alert) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Alert not found." });
      }

      await ctx.prisma.alert.update({
        where: { id: input.alertId },
        data: { acknowledgedAt: new Date() },
      });

      return { acknowledged: true };
    }),
});
